abstract: A data package for a SQLite database
author: Adam Kennedy <cpan@ali.as>
build_requires: 
  File::Path: 0
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Data-Package-SQLite
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  DBD::SQLite: 1.10
  DBI: 1.43
  Data::Package: 1.00
  File::ShareDir: 0.03
  Params::Util: 0.10
  perl: 5.005
version: 1.00
